class LilyPond
	VERSION = "2.12.2"

	def self.create_doc(params, instrument)
		<<DOC
\\header {
	title = \\markup \\center-column { "Site-reading for #{ Time.now }" }
	tagline = "Music generated by Baby::Got::Bach, BITCH!"
	instrument = #{ instrument::NAME }
	composer = "Baby::Got::Bach"
}

\\version "#{ VERSION }"
{ 
	\\tempo 4 = #{ params[:tempo] }
	\\time #{ params[:time] }
	\\clef #{ instrument::CLEF }
	#{ instrument.generate(params) } 
}
DOC
	end

end
