class LilyPond
    VERSION = "2.12.2"

    def self.create_doc(options, instrument)

<<SCORE
\\header {
    title = \\markup \\center-column { "Site-reading for #{ Time.now }" }
    tagline = "Music generated by Baby::Got::Bach! (difficulty: #{ options[:difficulty] })"
    instrument = "#{ instrument::NAME }"
    composer = "Baby::Got::Bach"
}

\\version "#{ VERSION }"

global = {
    \\tempo 4 = 120
    \\time #{ options[:time_sig] }
}

#{ instrument.generate(options) } 

SCORE
    end

end
