#!/usr/bin/env ruby

$:.unshift File.join(File.dirname(__FILE__), 'lib')
Dir[File.join(File.dirname(__FILE__), 'vendor', '**', 'lib')].each {|path| $:.unshift path }

require 'baby'

exit Baby::Got::Bach.run!(*ARGV)
