#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
class OptionsParser < Racc::Parser

module_eval(<<'...end options.y.rb/module_eval...', 'options.y.rb', 65)

def parse(filename)
	input = IO.readlines(filename)
	@tokens = input
	do_parse
end

def next_token
	@tokens.shift
end
...end options.y.rb/module_eval...
##### State transition tables begin ###

racc_action_table = [
   -57,   -57,   -57,   -57,    74,    75,    76,   -57,    50,    51,
    52,    53,    54,    55,    56,    57,    58,    59,    60,    61,
    62,    63,    64,    65,    66,    67,    68,    69,    70,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    74,
    75,    76,    74,    75,    76,    13,     4,     4,     4,     4,
     4,    50,    51,    52,    53,    54,    55,    56,    57,    58,
    59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
    69,    70,    35,    36,    37,    38,    39,    40,    41,    42,
    43,    44,    35,    36,    37,    38,    39,    40,    41,    42,
    43,    44,    35,    36,    37,    38,    39,    40,    41,    42,
    43,    44,    35,    36,    37,    38,    39,    40,    41,    42,
    43,    44,    20,    21,    22,    23,    24,    25,    26,    27,
    28,    74,    75,    76,    74,    75,    76,    85,    86,     4,
    71,    31,     4,     4,    17,     4,     4,     4,    10,     4,
     4,    46,     4,     4,     8,     5,     4 ]

racc_action_check = [
     0,     6,     2,    11,    79,    79,    79,    15,    32,    32,
    32,    32,    32,    32,    32,    32,    32,    32,    32,    32,
    32,    32,    32,    32,    32,    32,    32,    32,    32,    71,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    83,
    83,    83,    87,    87,    87,     7,     6,    11,     0,     2,
    15,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    49,    77,    77,    77,    77,    77,    77,    77,    77,
    77,    77,    34,    34,    34,    34,    34,    34,    34,    34,
    34,    34,    47,    47,    47,    47,    47,    47,    47,    47,
    47,    47,    18,    18,    18,    18,    18,    18,    18,    18,
    18,    18,    14,    14,    14,    14,    14,    14,    14,    14,
    14,    45,    45,    45,    88,    88,    88,    80,    80,    17,
    33,    16,    13,    46,    12,    48,     8,    19,     5,    78,
     4,    30,    81,    82,     3,     1,    31 ]

racc_action_pointer = [
   -41,   145,   -40,   103,    51,   138,   -43,     3,    47,   nil,
   nil,   -42,    90,    43,    65,   -39,    86,    40,    23,    48,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    95,    57,   -50,    87,     3,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    31,    44,    13,    46,    -7,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   -50,   nil,   nil,   nil,   nil,   nil,    -7,    50,   -86,
    71,    53,    54,   -51,   nil,   nil,   nil,   -48,    34,   nil,
   nil,   nil ]

racc_action_default = [
    -2,   -62,    -4,   -62,   -57,   -62,    -6,   -62,   -57,   -58,
    92,    -8,   -62,   -57,   -62,   -10,   -62,   -57,   -62,   -57,
   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,    -1,
   -62,   -57,   -62,   -62,   -45,   -47,   -48,   -49,   -50,   -51,
   -52,   -53,   -54,   -55,   -56,   -62,   -57,   -62,   -57,   -21,
   -24,   -25,   -26,   -27,   -28,   -29,   -30,   -31,   -32,   -33,
   -34,   -35,   -36,   -37,   -38,   -39,   -40,   -41,   -42,   -43,
   -44,   -62,   -46,    -3,   -59,   -60,   -61,   -62,   -57,   -62,
   -62,   -57,   -57,   -62,    -7,   -22,   -23,   -62,   -62,    -9,
    -5,   -11 ]

racc_goto_table = [
     3,    73,     7,    48,     9,    33,    12,    29,    14,    15,
    11,    16,    19,    18,     6,    30,     2,    32,     1,    45,
    80,    72,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    47,   nil,   nil,    78,    84,   nil,   nil,   nil,    89,
   nil,   nil,   nil,    90,    91,   nil,    77,   nil,    79,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    81,   nil,
   nil,   nil,   nil,   nil,    82,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    83,   nil,
   nil,    87,    88 ]

racc_goto_check = [
     7,     9,     7,    11,     7,    10,     7,     6,     7,     5,
     4,     7,     8,     7,     3,     7,     2,     7,     1,     7,
    11,    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     7,   nil,   nil,    10,     9,   nil,   nil,   nil,     9,
   nil,   nil,   nil,     9,     9,   nil,     7,   nil,     7,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    10,   nil,
   nil,   nil,   nil,   nil,    10,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     7,   nil,
   nil,     7,     7 ]

racc_goto_pointer = [
   nil,    18,    16,    12,     4,    -2,    -8,     0,    -2,   -44,
   -13,   -29,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    49,    34 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 94, :_reduce_1,
  0, 95, :_reduce_none,
  6, 95, :_reduce_3,
  0, 96, :_reduce_4,
  8, 96, :_reduce_5,
  0, 97, :_reduce_6,
  6, 97, :_reduce_7,
  0, 98, :_reduce_8,
  6, 98, :_reduce_9,
  0, 99, :_reduce_10,
  6, 99, :_reduce_11,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 104, :_reduce_none,
  3, 104, :_reduce_none,
  3, 104, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 103, :_reduce_none,
  2, 103, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  1, 106, :_reduce_none,
  0, 100, :_reduce_none,
  2, 100, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none ]

racc_reduce_n = 62

racc_shift_n = 92

racc_token_table = {
  false => 0,
  :error => 1,
  :AFLAT => 2,
  :ANAT => 3,
  :ASHARP => 4,
  :BFLAT => 5,
  :BNAT => 6,
  :BSHARP => 7,
  :CFLAT => 8,
  :CNAT => 9,
  :DFLAT => 10,
  :DNAT => 11,
  :DSHARP => 12,
  :EFLAT => 13,
  :ENAT => 14,
  :FFLAT => 15,
  :FNAT => 16,
  :FSHARP => 17,
  :GFLAT => 18,
  :GNAT => 19,
  :GSHARP => 20,
  :ZERO => 21,
  :ONE => 22,
  :TWO => 23,
  :THREE => 24,
  :FOUR => 25,
  :FIVE => 26,
  :SIX => 27,
  :SEVEN => 28,
  :EIGHT => 29,
  :NINE => 30,
  :SOPRECORDER => 31,
  :ALTRECORDER => 32,
  :CONCFLUTE => 33,
  :OBOE => 34,
  :BASSOON => 35,
  :VIOLIN => 36,
  :GUITAR => 37,
  :PIANO => 38,
  :MAJOR => 39,
  :MINOR => 40,
  "instrument:" => 41,
  "time signature:" => 42,
  "/" => 43,
  "key:" => 44,
  "length:" => 45,
  "difficulty:" => 46,
  "soprano recorder" => 47,
  "alto recorder" => 48,
  "concert flute" => 49,
  "oboe" => 50,
  "bassoon" => 51,
  "violin" => 52,
  "cello" => 53,
  "guitar" => 54,
  "piano" => 55,
  "major" => 56,
  "minor" => 57,
  "Ab" => 58,
  "A" => 59,
  "A#" => 60,
  "Bb" => 61,
  "B" => 62,
  "B#" => 63,
  "Cb" => 64,
  "C" => 65,
  "C#" => 66,
  "Db" => 67,
  "D" => 68,
  "D#" => 69,
  "Eb" => 70,
  "E" => 71,
  "E#" => 72,
  "Fb" => 73,
  "F" => 74,
  "F#" => 75,
  "Gb" => 76,
  "G" => 77,
  "G#" => 78,
  "0" => 79,
  "1" => 80,
  "2" => 81,
  "3" => 82,
  "4" => 83,
  "5" => 84,
  "6" => 85,
  "7" => 86,
  "8" => 87,
  "9" => 88,
  " " => 89,
  "\n" => 90,
  "\r" => 91,
  "\r\n" => 92 }

racc_nt_base = 93

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "AFLAT",
  "ANAT",
  "ASHARP",
  "BFLAT",
  "BNAT",
  "BSHARP",
  "CFLAT",
  "CNAT",
  "DFLAT",
  "DNAT",
  "DSHARP",
  "EFLAT",
  "ENAT",
  "FFLAT",
  "FNAT",
  "FSHARP",
  "GFLAT",
  "GNAT",
  "GSHARP",
  "ZERO",
  "ONE",
  "TWO",
  "THREE",
  "FOUR",
  "FIVE",
  "SIX",
  "SEVEN",
  "EIGHT",
  "NINE",
  "SOPRECORDER",
  "ALTRECORDER",
  "CONCFLUTE",
  "OBOE",
  "BASSOON",
  "VIOLIN",
  "GUITAR",
  "PIANO",
  "MAJOR",
  "MINOR",
  "\"instrument:\"",
  "\"time signature:\"",
  "\"/\"",
  "\"key:\"",
  "\"length:\"",
  "\"difficulty:\"",
  "\"soprano recorder\"",
  "\"alto recorder\"",
  "\"concert flute\"",
  "\"oboe\"",
  "\"bassoon\"",
  "\"violin\"",
  "\"cello\"",
  "\"guitar\"",
  "\"piano\"",
  "\"major\"",
  "\"minor\"",
  "\"Ab\"",
  "\"A\"",
  "\"A#\"",
  "\"Bb\"",
  "\"B\"",
  "\"B#\"",
  "\"Cb\"",
  "\"C\"",
  "\"C#\"",
  "\"Db\"",
  "\"D\"",
  "\"D#\"",
  "\"Eb\"",
  "\"E\"",
  "\"E#\"",
  "\"Fb\"",
  "\"F\"",
  "\"F#\"",
  "\"Gb\"",
  "\"G\"",
  "\"G#\"",
  "\"0\"",
  "\"1\"",
  "\"2\"",
  "\"3\"",
  "\"4\"",
  "\"5\"",
  "\"6\"",
  "\"7\"",
  "\"8\"",
  "\"9\"",
  "\" \"",
  "\"\\n\"",
  "\"\\r\"",
  "\"\\r\\n\"",
  "$start",
  "input",
  "instrument_spec",
  "time_spec",
  "key_spec",
  "length_spec",
  "difficulty_spec",
  "whitespace",
  "instr",
  "ls",
  "int",
  "key",
  "pitch",
  "digit" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'options.y.rb', 16)
  def _reduce_1(val, _values, result)
     result = val 
    result
  end
.,.,

# reduce 2 omitted

module_eval(<<'.,.,', 'options.y.rb', 19)
  def _reduce_3(val, _values, result)
     result = val[3] 
    result
  end
.,.,

module_eval(<<'.,.,', 'options.y.rb', 21)
  def _reduce_4(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'options.y.rb', 22)
  def _reduce_5(val, _values, result)
     result = val[3] + '/' + val[5] 
    result
  end
.,.,

module_eval(<<'.,.,', 'options.y.rb', 24)
  def _reduce_6(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'options.y.rb', 25)
  def _reduce_7(val, _values, result)
     result = val[3] 
    result
  end
.,.,

module_eval(<<'.,.,', 'options.y.rb', 27)
  def _reduce_8(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'options.y.rb', 28)
  def _reduce_9(val, _values, result)
     result = val[3] 
    result
  end
.,.,

module_eval(<<'.,.,', 'options.y.rb', 30)
  def _reduce_10(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'options.y.rb', 31)
  def _reduce_11(val, _values, result)
     result = val[3] 
    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class OptionsParser
